### ISSUE TITLE
Updating Week Navigation

### ISSUE THREAD

**Issue by MichealPearce** [bcranton/goldengoblet.net#27]
Hi! I was planning to update the week navigation but I wanted to make sure what I was looking to update is correct. The nav menu is the one at the top left of the page, correct?

![image](https://user-images.githubusercontent.com/8726457/88210666-8a54f780-cc22-11ea-9c16-ef4c5eb75711.png)

**Comment by bcranton** [comment]
Hey, that's the correct menu :) As you can see in your screenshot, its getting a bit long, even extending off the screen. So, wanted to rework it to something that is more elegent.

Thanks a lot for helping out!
